var randomnumber1=Math.floor(Math.random()*6+1);
var randomnumber2=Math.floor(Math.random()*6+1);
if(randomnumber1===randomnumber2){
  document.querySelector("h1").innerHTML="🤴Its a draw!🤴";

  if(randomnumber1===1){
    document.querySelector(".imgp1").src="dice1.png";
    document.querySelector(".imgp2").src="dice1.png";
  }
  if(randomnumber1===2){
    document.querySelector(".imgp1").src="dice2.png";
    document.querySelector(".imgp2").src="dice2.png";
  }
  if(randomnumber1===3){
    document.querySelector(".imgp1").src="dice3.png";
    document.querySelector(".imgp2").src="dice3.png";
  }
  if(randomnumber1===4){
    document.querySelector(".imgp1").src="dice4.png";
    document.querySelector(".imgp2").src="dice4.png";
  }
  if(randomnumber1===5){
    document.querySelector(".imgp1").src="dice5.png";
    document.querySelector(".imgp2").src="dice5.png";
  }
  if(randomnumber1===6){
    document.querySelector(".imgp1").src="dice6.png";
    document.querySelector(".imgp2").src="dice6.png";
  }
}
if(randomnumber1<randomnumber2){
  document.querySelector("h1").innerHTML="Player 2 wins!🤴";
  if(randomnumber1===1){
    document.querySelector(".imgp1").src="dice1.png";
  }
  if(randomnumber1===2){
    document.querySelector(".imgp1").src="dice2.png";
  }
  if(randomnumber1===3){
    document.querySelector(".imgp1").src="dice3.png";
  }
  if(randomnumber1===4){
    document.querySelector(".imgp1").src="dice4.png";
  }
  if(randomnumber1===5){
    document.querySelector(".imgp1").src="dice5.png";
  }
  if(randomnumber1===6){
    document.querySelector(".imgp1").src="dice6.png";
  }
  if(randomnumber1===1){
    document.querySelector(".imgp1").src="dice1.png";
  }
  if(randomnumber1===2){
    document.querySelector(".imgp1").src="dice2.png";
  }
  if(randomnumber1===3){
    document.querySelector(".imgp1").src="dice3.png";
  }
  if(randomnumber1===4){
    document.querySelector(".imgp1").src="dice4.png";
  }
  if(randomnumber1===5){
    document.querySelector(".imgp1").src="dice5.png";
  }
  if(randomnumber2===1){
    document.querySelector(".imgp2").src="dice1.png";
  }
  if(randomnumber2===2){
    document.querySelector(".imgp2").src="dice2.png";
  }
  if(randomnumber2===3){
    document.querySelector(".imgp2").src="dice3.png";
  }
  if(randomnumber2===4){
    document.querySelector(".imgp2").src="dice4.png";
  }
  if(randomnumber2===5){
    document.querySelector(".imgp2").src="dice5.png";
  }
  if(randomnumber2===6){
    document.querySelector(".imgp2").src="dice6.png";
  }

}
if(randomnumber1>randomnumber2){
  document.querySelector("h1").innerHTML="🤴Player 1 wins!";
  if(randomnumber1===1){
    document.querySelector(".imgp1").src="dice1.png";
  }
  if(randomnumber1===2){
    document.querySelector(".imgp1").src="dice2.png";
  }
  if(randomnumber1===3){
    document.querySelector(".imgp1").src="dice3.png";
  }
  if(randomnumber1===4){
    document.querySelector(".imgp1").src="dice4.png";
  }
  if(randomnumber1===5){
    document.querySelector(".imgp1").src="dice5.png";
  }
  if(randomnumber1===6){
    document.querySelector(".imgp1").src="dice6.png";
  }
  if(randomnumber1===1){
    document.querySelector(".imgp1").src="dice1.png";
  }
  if(randomnumber1===2){
    document.querySelector(".imgp1").src="dice2.png";
  }
  if(randomnumber1===3){
    document.querySelector(".imgp1").src="dice3.png";
  }
  if(randomnumber1===4){
    document.querySelector(".imgp1").src="dice4.png";
  }
  if(randomnumber1===5){
    document.querySelector(".imgp1").src="dice5.png";
  }
  if(randomnumber2===1){
    document.querySelector(".imgp2").src="dice1.png";
  }
  if(randomnumber2===2){
    document.querySelector(".imgp2").src="dice2.png";
  }
  if(randomnumber2===3){
    document.querySelector(".imgp2").src="dice3.png";
  }
  if(randomnumber2===4){
    document.querySelector(".imgp2").src="dice4.png";
  }
  if(randomnumber2===5){
    document.querySelector(".imgp2").src="dice5.png";
  }
  if(randomnumber2===6){
    document.querySelector(".imgp2").src="dice6.png";
  }
}
